# Generated by Django 5.0 on 2024-01-12 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('job_type', models.CharField(choices=[('intership', 'internship'), ('full-time', 'full-time'), ('part-time', 'part-time')], max_length=20)),
                ('location', models.CharField(choices=[('on-site', 'on-site'), ('remote', 'remote'), ('hybrid', 'hybrid')], max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
