# Generated by Django 5.0 on 2024-01-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Job',
        ),
    ]
