# Generated by Django 5.0 on 2024-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(max_length=120),
        ),
    ]
